# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98b532bc1106ba5eb8946ce90b1416a9b0a9b55ed52cabc6f40c91ed3855f2d9278af1253c11bc544d16c6dccffb715c759ef73276e28963880576d2f9c27047

test:
  secret_key_base: 6f67873be0c89e872a50e504822ce53757963e5bade1f29071b20530a14ace3e81a73585e2039da546f4f5b86f3a3ed4de7a40a451dc5b45ee4e6aad3d95c86d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
